%General Mission Analysis Tool(GMAT) Script
%Created: 2022-03-09 15:11:12


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
GMAT DefaultSC.DateFormat = TAIModJulian;
GMAT DefaultSC.Epoch = '21545';
GMAT DefaultSC.CoordinateSystem = EarthMJ2000Ec;
GMAT DefaultSC.DisplayStateType = Cartesian;
GMAT DefaultSC.X = 546507.3442558449;
GMAT DefaultSC.Y = -527978.380486028;
GMAT DefaultSC.Z = 531109.066836708;
GMAT DefaultSC.VX = -4.9220589268733;
GMAT DefaultSC.VY = 5.363165230979149;
GMAT DefaultSC.VZ = -5.22166308425181;
GMAT DefaultSC.DryMass = 850;
GMAT DefaultSC.Cd = 2.2;
GMAT DefaultSC.Cr = 1.8;
GMAT DefaultSC.DragArea = 15;
GMAT DefaultSC.SRPArea = 1;
GMAT DefaultSC.SPADDragScaleFactor = 1;
GMAT DefaultSC.SPADSRPScaleFactor = 1;
GMAT DefaultSC.NAIFId = -10000001;
GMAT DefaultSC.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC.OrbitColor = Red;
GMAT DefaultSC.TargetColor = Teal;
GMAT DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC.CdSigma = 1e+70;
GMAT DefaultSC.CrSigma = 1e+70;
GMAT DefaultSC.Id = 'SatId';
GMAT DefaultSC.Attitude = CoordinateSystemFixed;
GMAT DefaultSC.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC.ModelFile = 'aura.3ds';
GMAT DefaultSC.ModelOffsetX = 0;
GMAT DefaultSC.ModelOffsetY = 0;
GMAT DefaultSC.ModelOffsetZ = 0;
GMAT DefaultSC.ModelRotationX = 0;
GMAT DefaultSC.ModelRotationY = 0;
GMAT DefaultSC.ModelRotationZ = 0;
GMAT DefaultSC.ModelScale = 1;
GMAT DefaultSC.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC.EulerAngleSequence = '321';

Create Spacecraft DefaultSC_wTCM;
GMAT DefaultSC_wTCM.DateFormat = TAIModJulian;
GMAT DefaultSC_wTCM.Epoch = '21545';
GMAT DefaultSC_wTCM.CoordinateSystem = EarthMJ2000Ec;
GMAT DefaultSC_wTCM.DisplayStateType = Cartesian;
GMAT DefaultSC_wTCM.X = 546507.3442558449;
GMAT DefaultSC_wTCM.Y = -527978.380486028;
GMAT DefaultSC_wTCM.Z = 531109.066836708;
GMAT DefaultSC_wTCM.VX = -5.14496787802522;
GMAT DefaultSC_wTCM.VY = 5.14445848650899;
GMAT DefaultSC_wTCM.VZ = -5.144557245153842;
GMAT DefaultSC_wTCM.DryMass = 850;
GMAT DefaultSC_wTCM.Cd = 2.2;
GMAT DefaultSC_wTCM.Cr = 1.8;
GMAT DefaultSC_wTCM.DragArea = 15;
GMAT DefaultSC_wTCM.SRPArea = 1;
GMAT DefaultSC_wTCM.SPADDragScaleFactor = 1;
GMAT DefaultSC_wTCM.SPADSRPScaleFactor = 1;
GMAT DefaultSC_wTCM.NAIFId = -10000001;
GMAT DefaultSC_wTCM.NAIFIdReferenceFrame = -9000001;
GMAT DefaultSC_wTCM.OrbitColor = Red;
GMAT DefaultSC_wTCM.TargetColor = Teal;
GMAT DefaultSC_wTCM.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
GMAT DefaultSC_wTCM.CdSigma = 1e+70;
GMAT DefaultSC_wTCM.CrSigma = 1e+70;
GMAT DefaultSC_wTCM.Id = 'SatId';
GMAT DefaultSC_wTCM.Attitude = CoordinateSystemFixed;
GMAT DefaultSC_wTCM.SPADSRPInterpolationMethod = Bilinear;
GMAT DefaultSC_wTCM.SPADSRPScaleFactorSigma = 1e+70;
GMAT DefaultSC_wTCM.SPADDragInterpolationMethod = Bilinear;
GMAT DefaultSC_wTCM.SPADDragScaleFactorSigma = 1e+70;
GMAT DefaultSC_wTCM.ModelFile = 'aura.3ds';
GMAT DefaultSC_wTCM.ModelOffsetX = 0;
GMAT DefaultSC_wTCM.ModelOffsetY = 0;
GMAT DefaultSC_wTCM.ModelOffsetZ = 0;
GMAT DefaultSC_wTCM.ModelRotationX = 0;
GMAT DefaultSC_wTCM.ModelRotationY = 0;
GMAT DefaultSC_wTCM.ModelRotationZ = 0;
GMAT DefaultSC_wTCM.ModelScale = 1;
GMAT DefaultSC_wTCM.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC_wTCM.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC_wTCM.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC_wTCM.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Earth;
GMAT DefaultProp_ForceModel.PrimaryBodies = {Earth};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;
GMAT DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.Order = 4;
GMAT DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
GMAT DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
GMAT DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-12;
GMAT DefaultProp.MinStep = 0.001;
GMAT DefaultProp.MaxStep = 2700;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0 0 ];
GMAT DefaultOrbitView.Size = [ 0.706369982547993 0.9578675838349097 ];
GMAT DefaultOrbitView.RelativeZOrder = 138;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {DefaultSC, DefaultSC_wTCM, Earth};
GMAT DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.DrawObject = [ true true true ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.MaxPlotPoints = 20000;
GMAT DefaultOrbitView.ShowLabels = true;
GMAT DefaultOrbitView.ViewPointReference = Earth;
GMAT DefaultOrbitView.ViewPointVector = [ -300000 300000 300000 ];
GMAT DefaultOrbitView.ViewDirection = Earth;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC) DefaultProp(DefaultSC_wTCM) {DefaultSC.ElapsedSecs = 1};
%Propagate DefaultProp(DefaultSC) DefaultProp(DefaultSC_wTCM) {DefaultSC.ElapsedSecs = 102404.3818};
Propagate DefaultProp(DefaultSC) DefaultProp(DefaultSC_wTCM) {DefaultSC.ElapsedSecs = 102405.381807303, DefaultSC_wTCM.ElapsedSecs = 102405.381807303};
